export interface Question {
  id: number;
  text: string;
  options: string[];
  correctIndex: number;
  category: string;
  difficulty: "leicht" | "mittel" | "schwer";
}

export const questions: Question[] = [
  {
    id: 1,
    text: "Welche Stadt ist die Hauptstadt von Deutschland?",
    options: ["München", "Berlin", "Hamburg", "Frankfurt"],
    correctIndex: 1,
    category: "Geografie",
    difficulty: "leicht",
  },
  {
    id: 2,
    text: "Wie viele Bundesländer hat Deutschland?",
    options: ["14", "15", "16", "17"],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "leicht",
  },
  {
    id: 3,
    text: "Welches Tier ist auf dem Berliner Wappen?",
    options: ["Adler", "Löwe", "Bär", "Wolf"],
    correctIndex: 2,
    category: "Allgemeinwissen",
    difficulty: "leicht",
  },
  {
    id: 4,
    text: "In welchem Jahr fiel die Berliner Mauer?",
    options: ["1987", "1988", "1989", "1990"],
    correctIndex: 2,
    category: "Geschichte",
    difficulty: "leicht",
  },
  {
    id: 5,
    text: "Welcher Fluss fließt durch München?",
    options: ["Rhein", "Elbe", "Isar", "Donau"],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "mittel",
  },
  {
    id: 6,
    text: "Wer schrieb 'Die Leiden des jungen Werthers'?",
    options: ["Schiller", "Goethe", "Heine", "Kafka"],
    correctIndex: 1,
    category: "Literatur",
    difficulty: "mittel",
  },
  {
    id: 7,
    text: "Wie heißt das größte Volksfest der Welt?",
    options: ["Karneval", "Schützenfest", "Oktoberfest", "Kieler Woche"],
    correctIndex: 2,
    category: "Kultur",
    difficulty: "leicht",
  },
  {
    id: 8,
    text: "Welches Element hat das chemische Symbol 'Fe'?",
    options: ["Fluor", "Eisen", "Francium", "Fermium"],
    correctIndex: 1,
    category: "Wissenschaft",
    difficulty: "mittel",
  },
  {
    id: 9,
    text: "Wie viele Spieler hat eine Fußballmannschaft auf dem Feld?",
    options: ["9", "10", "11", "12"],
    correctIndex: 2,
    category: "Sport",
    difficulty: "leicht",
  },
  {
    id: 10,
    text: "Welcher Planet ist der Erde am nächsten?",
    options: ["Mars", "Venus", "Merkur", "Jupiter"],
    correctIndex: 1,
    category: "Wissenschaft",
    difficulty: "mittel",
  },
  {
    id: 11,
    text: "Wann wurde das Grundgesetz der Bundesrepublik Deutschland verkündet?",
    options: ["1945", "1947", "1949", "1951"],
    correctIndex: 2,
    category: "Geschichte",
    difficulty: "mittel",
  },
  {
    id: 12,
    text: "Welche Farben hat die deutsche Flagge?",
    options: [
      "Schwarz-Rot-Gold",
      "Schwarz-Rot-Gelb",
      "Rot-Weiß-Blau",
      "Schwarz-Weiß-Rot",
    ],
    correctIndex: 0,
    category: "Allgemeinwissen",
    difficulty: "leicht",
  },
  {
    id: 13,
    text: "Welches Instrument hat 88 Tasten?",
    options: ["Orgel", "Akkordeon", "Klavier", "Keyboard"],
    correctIndex: 2,
    category: "Musik",
    difficulty: "leicht",
  },
  {
    id: 14,
    text: "Wie heißt der höchste Berg Deutschlands?",
    options: ["Feldberg", "Brocken", "Zugspitze", "Watzmann"],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "leicht",
  },
  {
    id: 15,
    text: "Welches Land hat die meisten Einwohner?",
    options: ["USA", "Indien", "China", "Russland"],
    correctIndex: 1,
    category: "Geografie",
    difficulty: "mittel",
  },
  {
    id: 16,
    text: "Wie viele Zähne hat ein erwachsener Mensch normalerweise?",
    options: ["28", "30", "32", "34"],
    correctIndex: 2,
    category: "Wissenschaft",
    difficulty: "mittel",
  },
  {
    id: 17,
    text: "Welcher deutsche Komponist wurde in Bonn geboren?",
    options: ["Bach", "Beethoven", "Brahms", "Händel"],
    correctIndex: 1,
    category: "Musik",
    difficulty: "mittel",
  },
  {
    id: 18,
    text: "Was bedeutet 'HTML'?",
    options: [
      "Hyper Text Markup Language",
      "High Tech Modern Language",
      "Hyper Transfer Markup Language",
      "Home Tool Markup Language",
    ],
    correctIndex: 0,
    category: "Technik",
    difficulty: "mittel",
  },
  {
    id: 19,
    text: "In welchem Bundesland liegt der Schwarzwald?",
    options: ["Bayern", "Baden-Württemberg", "Hessen", "Rheinland-Pfalz"],
    correctIndex: 1,
    category: "Geografie",
    difficulty: "mittel",
  },
  {
    id: 20,
    text: "Welches Gas atmen Pflanzen ein?",
    options: ["Sauerstoff", "Stickstoff", "Kohlendioxid", "Wasserstoff"],
    correctIndex: 2,
    category: "Wissenschaft",
    difficulty: "leicht",
  },
  {
    id: 21,
    text: "Wie heißt die Währung der Schweiz?",
    options: ["Euro", "Schweizer Franken", "Krone", "Schilling"],
    correctIndex: 1,
    category: "Allgemeinwissen",
    difficulty: "leicht",
  },
  {
    id: 22,
    text: "Wer malte die Mona Lisa?",
    options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Rembrandt"],
    correctIndex: 2,
    category: "Kunst",
    difficulty: "leicht",
  },
  {
    id: 23,
    text: "Wie viele Kontinente gibt es?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "leicht",
  },
  {
    id: 24,
    text: "Welches Tier kann am schnellsten laufen?",
    options: ["Löwe", "Gepard", "Pferd", "Strauß"],
    correctIndex: 1,
    category: "Natur",
    difficulty: "leicht",
  },
  {
    id: 25,
    text: "In welcher Stadt steht der Kölner Dom?",
    options: ["Bonn", "Düsseldorf", "Köln", "Aachen"],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "leicht",
  },
  {
    id: 26,
    text: "Welcher Ozean ist der größte?",
    options: [
      "Atlantischer Ozean",
      "Indischer Ozean",
      "Pazifischer Ozean",
      "Arktischer Ozean",
    ],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "mittel",
  },
  {
    id: 27,
    text: "Was ist die Quadratwurzel von 144?",
    options: ["10", "11", "12", "14"],
    correctIndex: 2,
    category: "Mathematik",
    difficulty: "mittel",
  },
  {
    id: 28,
    text: "Welches Organ pumpt das Blut durch den Körper?",
    options: ["Lunge", "Leber", "Herz", "Niere"],
    correctIndex: 2,
    category: "Wissenschaft",
    difficulty: "leicht",
  },
  {
    id: 29,
    text: "Wie heißt Deutschlands längster Fluss?",
    options: ["Elbe", "Donau", "Rhein", "Weser"],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "mittel",
  },
  {
    id: 30,
    text: "Welches Land hat die Form eines Stiefels?",
    options: ["Spanien", "Griechenland", "Italien", "Portugal"],
    correctIndex: 2,
    category: "Geografie",
    difficulty: "leicht",
  },
];

export function getShuffledQuestions(count: number): Question[] {
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
